export enum SocketEventsEnum {
  boardsJoin = 'boards:join',
  boardsLeave = 'boards:leave',
  boardsUpdate = 'boards:update',
  boardsUpdateSucess = 'boards:updateSuccess',
  boardsUpdateFailure = 'boards:updateFailure',
  boardDelete = 'board:delete',
  boardDeleteSucess = 'board:deleteSuccess',
  boardDeleteFailure = 'board:deleteFailure',
  columnsCreate = 'columns:create',
  columnsCreateSucess = 'columns:createSuccess',
  columnsCreateFailure = 'columns:createFailure',
  columnDelete = 'column:delete',
  columnDeleteSucess = 'column:deleteSuccess',
  columnDeleteFailure = 'column:deleteFailure',
  tasksCreate = 'tasks:create',
  tasksCreateSucess = 'tasks:createSuccess',
  tasksCreateFailure = 'tasks:createFailure',
}
